model: vit
mode: big_class
exp: COLOR
run_name: 'ViT for preprocessing (with latent crack)'
exp_log: 'ViT for preprocessing (with latent crack)'
dataset_dir: '/hdd_ext/kkokkobot/data/Classification/COLOR_w_LatentCrack/bigclass'
pre_trained: ''
base_lr: 0.0001
lr_scheduler: Cosine
grad_clipping: 1
n_epochs: 50
batch_size: 64
loss: CrossEntropy
optim: AdamW
wd: 0.00000001
auto_augment: False
is_mixup: True
