model: swin
mode: big_class
exp: MONO
run_name: 'SWIN_MONO1213_wo_latentcrack'
exp_log: 'SWIN_MONO1213_wo_latentcrack'
dataset_dir: '/hdd_ext/kkokkobot/data/Classification/MONO_1213_wo_latentcrack/bigclass'
pre_trained: ''
base_lr: 0.00001
lr_scheduler: Cosine
grad_clipping: 1
weighted_loss: False
n_epochs: 100
batch_size: 64
loss: CrossEntropy
optim: AdamW
wd: 0.00000001
auto_augment: False
is_mixup: True
